name: Build wheels

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build wheels
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/386, linux/arm64, linux/arm/v6, linux/arm/v7]
    steps:
      - name: Declare platform
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM=${platform//\//-}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build wheels
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.wheels
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=local,dest=/tmp/wheels

      - name: Transfer wheels
        uses: actions/cache@v4
        with:
          path: /tmp/wheels
          key: wheels-${{ env.PLATFORM }}-${{ github.run_id }}
          restore-keys: |
            wheels-${{ env.PLATFORM }}-
